<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_1</name>
   <tag></tag>
   <elementGuidId>5fc8a612-cf3f-4ced-9197-3f4eeebd41c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tsf&quot;]/div[2]/div[3]/center/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tsf&quot;]/div[2]/div[3]/center/input[1]</value>
   </webElementProperties>
</WebElementEntity>
