<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EndDateIntervention</name>
   <tag></tag>
   <elementGuidId>e58088f4-f66c-4298-8965-98f5d50f5623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@id='interventionStartDate1']//following::img[@name='imgCalendar'])[3]</value>
   </webElementProperties>
</WebElementEntity>
