<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InterventionTextArea</name>
   <tag></tag>
   <elementGuidId>70ae3b80-d48e-4b9a-8a4b-d35f33771e07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id=&quot;interventionPlanID1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@id=&quot;interventionPlanID1&quot;]</value>
   </webElementProperties>
</WebElementEntity>
