<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StartDateIntervention</name>
   <tag></tag>
   <elementGuidId>5247ae69-b1eb-44c9-b75f-d7722fce0283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@id='interventionStartDate1']//following::img[@name='imgCalendar'])[1]</value>
   </webElementProperties>
</WebElementEntity>
